apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: nginx-replicaset
    labels:
        app: nginx
        type: frontend
spec:
    replicas: 3
    selector:
      matchLabels:
        app: nginx
        type: frontend
    template:
        metadata:
            labels:
                app: nginx
                type: frontend
        spec:
            containers:
            - name: nginx-container
              image: nginx:latest
              ports:
              - containerPort: 80